plugins {}

import java.nio.file.Files
import java.nio.file.StandardOpenOption

val generateBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/source/buildInfo/kotlin").get().asFile
    val pkg = "com.bepiscorp.ktools.core"
    val versionValue = project.version.toString()

    outputs.dir(outputDir)

    doLast {
        val pkgDir = outputDir.resolve(pkg.replace('.', '/'))
        pkgDir.mkdirs()
        val file = pkgDir.resolve("BuildInfo.kt").toPath()
        val content = """
            package $pkg

            /** Build-time constants generated by Gradle. */
            object BuildInfo {
                const val version: String = "$versionValue"
            }
        """.trimIndent()
        Files.write(
            file,
            content.toByteArray(),
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING,
            StandardOpenOption.WRITE,
        )
    }
}

sourceSets {
    val main by getting {
        kotlin.srcDir(layout.buildDirectory.dir("generated/source/buildInfo/kotlin"))
    }
}

tasks.named("compileKotlin").configure {
    dependsOn(generateBuildInfo)
}
